name: deploy my site
on:
  push:
    branches:
      - main
jobs:
  generate-my-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno environment
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Build site
        run: deno task build
      - name: Upload artifact
        id: mysite
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'

  deploy-my-site:
    runs-on: ubuntu-latest
    needs:
      - generate-my-site
    permissions:
      pages: write
      id-token: write
    environment:
      name: MySite
      url: ${{ steps.mysite.outputs.page_url }}
    steps:
      - name: Deploy to GitHub pages
        id: mysite
        uses: actions/deploy-pages@v4
